### ISSUE TITLE
Calibration in changing temperatures (eg, outside)

### ISSUE THREAD

**Issue by inktomi** [MichaelS11/go-hx711#4]
Thank you for the great library - it seems to work really well in my use so far. I do need to use this outside though, where temperatures will range from below 0F to near 100F. As you point out that temperature affects calibration, and as my device will be outside where it can't be calibrated as the temperature changes - what would be your suggestion? 

I don't actually need to know the weight, I'm more concerned about the _change_ in weight. Maybe a single calibration is enough for that use? 

I'm trying to detect when a squirrel jumps onto a bird feeder.. so the bird feeder will change in weight over time as the seeds are eaten, and it'll suddenly change when birds land and fly away, but there will be a LARGE change when a squirrel jumps onto the feeder.. and that's what I'm trying to detect. 

Do you think this is a reasonable use case? Do you have any tips for a new user of the HX711 and Load Cells? Thank you!

**Comment by MichaelS11** [comment]
Glad you are finding it useful, that is great! :)

I would suggestion just calibrating it every hour or so since you only need the change in weight. Would need to write the details on your own, but should not be to hard. If the weight has not change by much over the last say 3 minutes, they adjust the calibration so the weight is back to zero again. (`AdjustZero`) Would think that adjusting the magnitude the first time and then manually every few months would be fine. (`AdjustScale`)

Would also suggest experimenting over a couple of days. Storing the values over a few days and graphing them. See what you get. Welcome to share your results here.

**Comment by inktomi** [comment]
I see - so I could keep adjusting the `AdjustZero` weight based on the rolling average value and use a single `AdjustScale`. I'm making this little device to scare squirrels off my parent's bird feeder - so I won't have direct access to it to manually calibrate it unfortunately - though maaaaybe I could get the full-of-seed weight and then add a little button that my parents could press every time they fill it up which will recalibrate it all using the known full-of-seed weight. 

Thanks for getting back to me. I'm pushing all my code up to https://github.com/inktomi/squirrel as I go.

**Comment by MichaelS11** [comment]
There you go :)

Another option is do some temperature drift calcuations. Can Goggle hx711 temperature drift compensation. I found the Honeybee Hive Monitoring project an intresting read when I was orginaly working on this probject. 
https://hackaday.io/project/1741/logs

Also, highly suggest you check out this video, which is mostly off topic but great.
https://www.youtube.com/watch?v=hFZFjoX2cGg

**Comment by MichaelS11** [comment]
@inktomi All good? Can you close this out?

**Comment by inktomi** [comment]
Yes, apologies. Thank you very much!
